//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public decimal Ticket_Number { get; set; }
        public string User_ID { get; set; }
        public string Class { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Seat_Number { get; set; }
        public string Boarding_Gate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Flight_Number { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual User User { get; set; }
    }
}
